### ISSUE TITLE
Cannot build project

### ISSUE THREAD

**Issue by trietbui85** [pillfill/hiding-passwords-android#2]
I'm using Android Studio 1.3 RC4.

When compile project, I receive this error:

> Incompatible Android Plugin Version: Android plugin version 1.2.3 is not compatible with the NDK support. Please use the experimental plugin.

And after changing Gradle plugin to `com.android.tools.build:gradle-experimental:0.1.0`, then the next error is:

> Gradle sync failed: Plugin with id 'com.android.application' not found

Could you please confirm this project is compiled successful in your side?

**Comment by rammic** [comment]
I'm getting working builds in Android Studio (just upgraded to 1.3 final) despite the warning. Also working from the command line with:

`gradle clean assembleX86Debug`

I tried to [pull in the experimental plugin](https://sites.google.com/a/android.com/tools/tech-docs/new-build-system/gradle-experimental) but ran into a bunch of issues with the new gradle DSL. Try to do a build from your terminal and let me know how it goes.

**Comment by trietbui85** [comment]
This morning I update my Android Studio to v1.3. After set `ndk.dir` in `local.properties` but don't use Gradle experimental plugin, I can compile and run this app although still have some warnings.

Thank you for supporting. You're free to close this issue.

**Comment by rammic** [comment]
No problem. Hopefully this project is helpful in some meaningful way!
